### ISSUE TITLE
CreatePayment request validation has a bug

### ISSUE THREAD

**Issue by tominurmiainen** [paytrail/paytrail-js-sdk#39]
Hi,
It seems there is a bug for validating create payment request if groups are specified:

@IsOptional()
@IsArray()
@ValidateNested()
public groups?: PaymentMethodGroup[]

This will fail for ValidateNested(). Should it be something like this:

@IsArray()
@IsOptional()
@IsEnum(PaymentMethodGroup, { each: true })
public groups?: PaymentMethodGroup[]

**Comment by kotivuori** [comment]
Thanks for reporting @tominurmiainen. We will fix this
